# Generated by Django 4.0.6 on 2022-07-15 10:59

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('slug', models.SlugField(max_length=300, null=True)),
                ('brand_logo', models.ImageField(blank=True, null=True, upload_to='media/products/brands/logos')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, null=True)),
                ('featured_image', models.ImageField(null=True, upload_to='media/product_imgs')),
                ('product_image_1', models.ImageField(blank=True, max_length=3000, null=True, upload_to='media/product_imgs')),
                ('product_image_2', models.ImageField(blank=True, max_length=3000, null=True, upload_to='media/product_imgs')),
                ('product_image_3', models.ImageField(blank=True, max_length=3000, null=True, upload_to='media/product_imgs')),
                ('product_image_4', models.ImageField(blank=True, max_length=3000, null=True, upload_to='media/product_imgs')),
                ('product_image_5', models.ImageField(blank=True, max_length=3000, null=True, upload_to='media/product_imgs')),
                ('product_image_6', models.ImageField(blank=True, max_length=3000, null=True, upload_to='media/product_imgs')),
                ('product_image_7', models.ImageField(blank=True, max_length=3000, null=True, upload_to='media/product_imgs')),
                ('sku', models.CharField(blank=True, max_length=100, null=True, verbose_name='SKU')),
                ('upc', models.CharField(blank=True, max_length=100, null=True, verbose_name='UPC')),
                ('short_description', ckeditor.fields.RichTextField(blank=True, max_length=30000, null=True)),
                ('fulll_description', ckeditor.fields.RichTextField(blank=True, max_length=300000, null=True)),
                ('bullet_description_list', ckeditor.fields.RichTextField(blank=True, max_length=30000, null=True)),
                ('bullet_specifications_list', ckeditor.fields.RichTextField(blank=True, max_length=30000, null=True)),
                ('price_regular', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Regular price ')),
                ('price_sale', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Sale price')),
                ('amz_price_regular', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('amz_price_sale', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('wal_price_regular', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('wal_price_sale', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, null=True)),
                ('amazon', models.CharField(blank=True, help_text='Amazon', max_length=400, null=True)),
                ('walmart', models.CharField(blank=True, max_length=400, null=True, verbose_name='Walmart')),
                ('ebay', models.CharField(blank=True, max_length=400, null=True, verbose_name='Ebay')),
                ('newegg', models.CharField(blank=True, max_length=400, null=True, verbose_name='Newegg')),
                ('etsy', models.CharField(blank=True, max_length=400, null=True, verbose_name='Etsy')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ecommerce.brand')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ecommerce.category')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
